import { v4 as uuidv4 } from 'uuid'
import {Column} from "@/components";
export const columns: Column[] = [
    {
        key: 'title',
        title: 'Name',
        sortable: true,
    },
    {
        key: 'cardsCount',
        title: 'Cards',
        sortable: true,
    },
    {
        key: 'updated',
        title: 'Last Updated',
        sortable: true
    },
    {
        key: 'createdBy',
        title: 'Created by',
        sortable: true,
    },
    {
        key: 'options',
        title: '',
        sortable: false
    },
]
export const data = [
    {
        id: uuidv4(),
        title: 'Project A',
        cardsCount: 10,
        updated: '2023-07-07',
        createdBy: 'John Doe',
        editable: false,
    },
    {
        id: uuidv4(),
        title: 'Project B',
        cardsCount: 5,
        updated: '2023-07-06',
        createdBy: 'Jane Smith',
        editable: true,
    },
    {
        id: uuidv4(),
        title: 'Project C',
        cardsCount: 8,
        updated: '2023-07-05',
        createdBy: 'Alice Johnson',
        editable: false,
    },
    {
        id: uuidv4(),
        title: 'Project D',
        cardsCount: 3,
        updated: '2023-07-07',
        createdBy: 'Bob Anderson',
        editable: true,
    },
    {
        id: uuidv4(),
        title: 'Project E',
        cardsCount: 12,
        updated: '2023-07-04',
        createdBy: 'Emma Davis',
        editable: false,
    },
    {
        id: uuidv4(),
        title: 'Project A',
        cardsCount: 10,
        updated: '2023-07-07',
        createdBy: 'John Doe',
        editable: false,
    },
    {
        id: uuidv4(),
        title: 'Project B',
        cardsCount: 5,
        updated: '2023-07-06',
        createdBy: 'Jane Smith',
        editable: true,
    },
    {
        id: uuidv4(),
        title: 'Project C',
        cardsCount: 8,
        updated: '2023-07-05',
        createdBy: 'Alice Johnson',
        editable: false,
    },
    {
        id: uuidv4(),
        title: 'Project D',
        cardsCount: 3,
        updated: '2023-07-07',
        createdBy: 'Bob Anderson',
        editable: true,
    },
    {
        id: uuidv4(),
        title: 'Project E',
        cardsCount: 12,
        updated: '2023-07-04',
        createdBy: 'Emma Davis',
        editable: false,
    },
    {
        id: uuidv4(),
        title: 'Project A',
        cardsCount: 10,
        updated: '2023-07-07',
        createdBy: 'John Doe',
        editable: false,
    },
    {
        id: uuidv4(),
        title: 'Project B',
        cardsCount: 5,
        updated: '2023-07-06',
        createdBy: 'Jane Smith',
        editable: true,
    },
    {
        id: uuidv4(),
        title: 'Project C',
        cardsCount: 8,
        updated: '2023-07-05',
        createdBy: 'Alice Johnson',
        editable: false,
    },
    {
        id: uuidv4(),
        title: 'Project D',
        cardsCount: 3,
        updated: '2023-07-07',
        createdBy: 'Bob Anderson',
        editable: true,
    },
    {
        id: uuidv4(),
        title: 'Project E',
        cardsCount: 12,
        updated: '2023-07-04',
        createdBy: 'Emma Davis',
        editable: false,
    },
    {
        id: uuidv4(),
        title: 'Project A',
        cardsCount: 10,
        updated: '2023-07-07',
        createdBy: 'John Doe',
        editable: false,
    },
    {
        id: uuidv4(),
        title: 'Project B',
        cardsCount: 5,
        updated: '2023-07-06',
        createdBy: 'Jane Smith',
        editable: true,
    },
    {
        id: uuidv4(),
        title: 'Project C',
        cardsCount: 8,
        updated: '2023-07-05',
        createdBy: 'Alice Johnson',
        editable: false,
    },
    {
        id: uuidv4(),
        title: 'Project D',
        cardsCount: 3,
        updated: '2023-07-07',
        createdBy: 'Bob Anderson',
        editable: true,
    },
    {
        id: uuidv4(),
        title: 'Project E',
        cardsCount: 12,
        updated: '2023-07-04',
        createdBy: 'Emma Davis',
        editable: false,
    },
]